### ISSUE TITLE
Returns 403 forbidden

### ISSUE THREAD

**Issue by AdrianRibao** [MarvAmBass/docker-piwik#15]
I get this error:

    directory index of "/usr/share/nginx/html/" is forbidden

in the container.

**Comment by MarvAmBass** [comment]
'kay

please post the logs and how you started the container

**Comment by AdrianRibao** [comment]
Logs:

    2015/10/21 09:33:03 [error] 38#38: *3 directory index of "/usr/share/nginx/html/" is forbidden, client: 172.17.42.1, server: , request: "GET / HTTP/1.0", host: "[myhost]" 172.17.42.1 - - [21/Oct/2015:09:33:03 +0000] "GET / HTTP/1.0" 403 564 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36"

I have started the container with my ansible provisioning code, nothing special, like in the docs, linking to a mysql container . The only thing I changed in ports is the local port: 9010:80 and 9011:443 but I think that has nothing to do with it.

**Comment by AdrianRibao** [comment]
I forgot to mention that I'm migrating a current piwik installation, so in the mysql container I have the current piwik site. That's why I didn't set any environment variables.

**Comment by AdrianRibao** [comment]
I think that the problem is that I forgot to add /piwik to the host, sorry.

I think that can be changed with PIWIK_RELATIVE_URL_ROOT

**Comment by MarvAmBass** [comment]
great and simple.

so it works now? I'll close this issue then

**Comment by AdrianRibao** [comment]
yes, you can close it, thanks
