### ISSUE TITLE
Update image on Docker Hub to use Piwik 2.15.0

### ISSUE THREAD

**Issue by bigzachattack** [MarvAmBass/docker-piwik#16]
Piwik 2.15.0 is now out.  It has improvements for performance and to the UI.

**Comment by MarvAmBass** [comment]
and I'm on it ;), hope nothing breaks ;)

**Comment by bigzachattack** [comment]
Pulled down the new image and everything seems to work. Thanks!

**Comment by MarvAmBass** [comment]
nice thanks for testing, I'll close this then.

and i should look for a automation of docker container creation...
