### ISSUE TITLE
Update image for piwik 2.16

### ISSUE THREAD

**Issue by AdrianRibao** [MarvAmBass/docker-piwik#19]
Piwik new version is now available.

Could you push the new image please? I think there are no big changes needed.

It would be great if its also tagged.

Thanks!

**Comment by Kiina** [comment]
Maybe this repo should set a version variable, pull from https://github.com/piwik/piwik/archive/VERSION.zip and tag images according to piwik version on docker hub.

**Comment by MarvAmBass** [comment]
done, and tagged
